config/routes.rb
Rails.application.routes.draw do
  resources :sales
  resources :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
 # root to: "home#index"

end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
class Client < ApplicationRecord

  has_many :sales
  belongs_to :source
  belongs_to :rep


def number_of_sales
  sales.count 
end 

  
end

app/models/company_location.rb
class CompanyLocation < ApplicationRecord
  
    has_many :sales
    
def name
   location_name
end


end

app/models/product_company.rb
class ProductCompany < ApplicationRecord
    has_many :sales

  
end

app/models/product_type.rb
class ProductType < ApplicationRecord
    has_many :sales

end

app/models/rep.rb
class Rep < ApplicationRecord
  
  has_many :sales
  has_many :clients

end

app/models/report.rb
class Report 
attr_reader :sales


def initialize(sales)
  @sales = sales 
end 

#New Clients

def number_of_new_clients 
  new_client_group.count
end 

def new_client_group
    new_clients.pluck(:client_id).uniq
end 

def new_clients
  @sales.where(new_client: true)
end 

 def new_client_revenue
   new_clients.sum(:first_year_comp)
 end 
 
 def new_clients_aum
   new_clients.sum(:opening_amount)
 end 
 


#Exisiting Clients In Motion 
 def existing_clients
   @sales.where(new_client: false)
 end 
 
 def exisiting_client_in_motion_revenue
   existing_clients.where(new_money: false).sum(:first_year_comp)
 end 
 
 def exisiting_client_in_motion_aum
   existing_clients.where(new_money: false).sum(:opening_amount)
 end 

#Exisiting Clients New Money 
def existing_clients_new_revenue 
   existing_clients.where(new_money: true).sum(:first_year_comp)
end 

def existing_clients_new_aum 
   existing_clients.where(new_money: true).sum(:opening_amount)
end 

# totals 
def total_sales_revenue  
  @sales.sum(:first_year_comp)
end 

def total_aum 
    @sales.sum(:opening_amount)
end 

def total_new_revenue 
  existing_clients_new_revenue + new_client_revenue
end 

def total_new_aum
  new_clients_aum + existing_clients_new_aum
end 







 

end 

app/models/sale.rb
class Sale < ApplicationRecord
  belongs_to :rep 
  belongs_to :product_company 
  belongs_to :company_location
  belongs_to :product_type
  belongs_to :source 
  belongs_to :client

end

app/models/source.rb
class Source < ApplicationRecord
  
    has_many :sales
    has_many :clients

    
def name
   source_name
end

  
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/sales_controller.rb
class SalesController < InheritedResources::Base

  private

    def sale_params
      params.require(:sale).permit(:name, :new_client, :client_on, :new_money, :sales_rep, :product, :source, :opening_amount, :first_year_comp, :renewal_comp, :user)
    end

end

app/controllers/users_controller.rb
class UsersController < InheritedResources::Base

  private

    def user_params
      params.require(:user).permit(:name, :email)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/clients/_sales.html.erb
<h3> Total Sales: <%= @client.sales.count %> </h3>
<h3> Client Lost: <%= @client.lost %> </h3>

<h1>Sales</h1>

<table>
  <thead>
    <tr>
      <th>Rep Name</th>
      <th>Opening Amount</th>
      <th>First Year Comp</th>
      <th>Issued On </th>
      <th>Source</th>
      <th>Product Company</th>
      <th>Reacurring</th>
      <th>New Money</th>
      <th>New Client</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @client.sales.each do |sale|%>
      <tr>
        <td><%= sale.rep.name %></td>
        <td><%= number_to_currency(sale.opening_amount) %></td>
        <td><%= number_to_currency(sale.first_year_comp) %></td>
        <td><%= sale.issued_on %></td>
        <td><%= sale.source.name %></td>
        <td><%= sale.product_company.name %></td>
        <td><%= sale.recurring %></td>
        <td><%= sale.new_money %></td>
        <td><%= sale.new_client %></td>
        <td><%= link_to "Edit", edit_admin_sale_path(sale) %></td>
        <td><%= link_to "Destroy", sale, method: :delete, data: { confirm: "Are you sure?" } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/sales/_form.html.erb
<%= form_with(model: @sale) do |form| %>
  <% if @sale.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sale.errors.count, "error") %> prohibited this sale from being saved:</h2>

      <ul>
        <% @sale.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :new_client %>
    <%= form.check_box :new_client %>
  </div>

  <div class="field">
    <%= form.label :client_on %>
    <%= form.datetime_select :client_on %>
  </div>

  <div class="field">
    <%= form.label :new_money %>
    <%= form.check_box :new_money %>
  </div>

  <div class="field">
    <%= form.label :sales_rep %>
    <%= form.text_field :sales_rep %>
  </div>

  <div class="field">
    <%= form.label :product %>
    <%= form.text_field :product %>
  </div>

  <div class="field">
    <%= form.label :source %>
    <%= form.text_field :source %>
  </div>

  <div class="field">
    <%= form.label :opening_amount %>
    <%= form.number_field :opening_amount %>
  </div>

  <div class="field">
    <%= form.label :first_year_comp %>
    <%= form.number_field :first_year_comp %>
  </div>

  <div class="field">
    <%= form.label :renewal_comp %>
    <%= form.number_field :renewal_comp %>
  </div>

  <div class="field">
    <%= form.label :user %>
    <%= form.text_field :user %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/sales/view_report.html.erb
<h1>New Clients</h1>
<p> Total Clients New Clients: <%= @report.number_of_new_clients %> </p>
<p> AUM From New Clients: <%= number_to_currency(@report.new_clients_aum) %> </p>
<p> Revenue From New Clients: <%= number_to_currency(@report.new_client_revenue) %> </p>

<h1>Exisiting Clients In Motion </h1>
<p> Total AUM from exisiting clients <%= number_to_currency(@report.exisiting_client_in_motion_aum) %> </p>
<p> Total Revenue from exisiting clients <%= number_to_currency(@report.exisiting_client_in_motion_revenue) %> </p>

<h1>Exisiting Clients New Money</h1>
<p> Total New AUM from exisiting clients <%= number_to_currency(@report.existing_clients_new_aum) %> </p>
<p> Total New Revenue from exisiting clients <%= number_to_currency(@report.existing_clients_new_revenue) %> </p>

<h1>Totals</h1>
<p> Total AUM <%= number_to_currency(@report.total_aum) %> </p>
<p> Total Sales Revenue <%= number_to_currency(@report.total_sales_revenue) %> </p>
<p> Total New AUM  <%= number_to_currency(@report.total_new_aum) %> </p>
<p> Total New Revenue <%= number_to_currency(@report.total_new_revenue) %> </p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MedallionReports</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/sales/_form.html.erb
<%= form_with(model: sale) do |form| %>
  <% if sale.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sale.errors.count, "error") %> prohibited this sale from being saved:</h2>

      <ul>
        <% sale.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :new_client %>
    <%= form.check_box :new_client %>
  </div>

  <div class="field">
    <%= form.label :client_on %>
    <%= form.datetime_select :client_on %>
  </div>

  <div class="field">
    <%= form.label :new_money %>
    <%= form.check_box :new_money %>
  </div>

  <div class="field">
    <%= form.label :sales_rep %>
    <%= form.text_field :sales_rep %>
  </div>

  <div class="field">
    <%= form.label :product %>
    <%= form.text_field :product %>
  </div>

  <div class="field">
    <%= form.label :source %>
    <%= form.text_field :source %>
  </div>

  <div class="field">
    <%= form.label :opening_amount %>
    <%= form.number_field :opening_amount %>
  </div>

  <div class="field">
    <%= form.label :first_year_comp %>
    <%= form.number_field :first_year_comp %>
  </div>

  <div class="field">
    <%= form.label :renewal_comp %>
    <%= form.number_field :renewal_comp %>
  </div>

  <div class="field">
    <%= form.label :user %>
    <%= form.text_field :user %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/sales/edit.html.erb
<h1>Editing Sale</h1>

<%= render 'form', sale: @sale %>

<%= link_to 'Show', @sale %> |
<%= link_to 'Back', sales_path %>

app/views/sales/index.html.erb
<h1>Sales</h1>

<h1> <%= @sales.count </h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>New client</th>
      <th>Client on</th>
      <th>New money</th>
      <th>Sales rep</th>
      <th>Product</th>
      <th>Source</th>
      <th>Opening amount</th>
      <th>First year comp</th>
      <th>Renewal comp</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sales.each do |sale| %>
      <tr>
        <td><%= sale.name %></td>
        <td><%= sale.new_client %></td>
        <td><%= sale.client_on %></td>
        <td><%= sale.new_money %></td>
        <td><%= sale.sales_rep %></td>
        <td><%= sale.product %></td>
        <td><%= sale.source %></td>
        <td><%= sale.opening_amount %></td>
        <td><%= sale.first_year_comp %></td>
        <td><%= sale.renewal_comp %></td>
        <td><%= link_to 'Show', sale %></td>
        <td><%= link_to 'Edit', edit_sale_path(sale) %></td>
        <td><%= link_to 'Destroy', sale, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sale', new_sale_path %>

app/views/sales/new.html.erb
<h1>New Sale</h1>

<%= render 'form', sale: @sale %>

<%= link_to 'Back', sales_path %>

app/views/sales/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @sale.name %>
</p>

<p>
  <strong>New client:</strong>
  <%= @sale.new_client %>
</p>

<p>
  <strong>Client on:</strong>
  <%= @sale.client_on %>
</p>

<p>
  <strong>New money:</strong>
  <%= @sale.new_money %>
</p>

<p>
  <strong>Sales rep:</strong>
  <%= @sale.sales_rep %>
</p>

<p>
  <strong>Product:</strong>
  <%= @sale.product %>
</p>

<p>
  <strong>Source:</strong>
  <%= @sale.source %>
</p>

<p>
  <strong>Opening amount:</strong>
  <%= @sale.opening_amount %>
</p>

<p>
  <strong>First year comp:</strong>
  <%= @sale.first_year_comp %>
</p>

<p>
  <strong>Renewal comp:</strong>
  <%= @sale.renewal_comp %>
</p>

<p>
  <strong>User:</strong>
  <%= @sale.user %>
</p>

<%= link_to 'Edit', edit_sale_path(@sale) %> |
<%= link_to 'Back', sales_path %>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>